import "Contact.idl";

namespace DairyApp
{
    [default_interface]
    runtimeclass TaskPage : Microsoft.UI.Xaml.Controls.Page
    {
        TaskPage();
        Int32 MyProperty;

        Windows.Foundation.Collections.IObservableVector<Contact> Contacts{ get; };
    }
}
